#!/bin/bash
# file: admin_job
# rbd offline recovery tool
# author: min chen(minchen@ubuntukylin.com) 2014 2015

my_dir=$(dirname "$0")

. $my_dir/common_h
. $my_dir/metadata_h
. $my_dir/epoch_h
. $my_dir/database_h

#scp files from admin node to osd node
file1=common_h
file2=metadata_h
file3=epoch_h
file4=osd_job

#------------ admin node's action -------------

function scp_file()
{
  local func="scp_file"
  file=$1
  if [ "$1"x = ""x ];then
    echo "$func: not file input"
    exit
  fi
  for host in `cat $osd_host`
  do
  {
    echo "$func: $host"
    scp $ssh_option $file $host:$job_path  1>/dev/null
  } &
  done
}

function scp_files()
{
  local func="scp_files"
  for host in `cat $osd_host`
  do
  {
    echo "$func: $host"
    scp $ssh_option $file1 $host:$job_path
    scp $ssh_option $file2 $host:$job_path
    scp $ssh_option $file3 $host:$job_path
    scp $ssh_option $file4 $host:$job_path
  } &
  done
  wait
  echo "$func: finish"
}

function scatter_node_jobs()
{
  local func="scatter_node_jobs"
  local host=
  local data_path=
  echo "$func ..."
  while read line
  do
  {
    host=`echo $line|awk '{print $1}'`
    data_path=`echo $line|awk '{print $2}'`
    check_osd_process $host

    cmd="mkdir -p $job_path"
    ssh $ssh_option $host $cmd
    scp $ssh_option $file1 $host:$job_path  >/dev/null
    scp $ssh_option $file2 $host:$job_path  >/dev/null
    scp $ssh_option $file3 $host:$job_path  >/dev/null
    scp $ssh_option $file4 $host:$job_path  >/dev/null
      
    cmd1="bash $job_path/osd_job do_omap_list $data_path"
    cmd2="bash $job_path/osd_job do_pg_epoch $data_path"
    cmd3="bash $job_path/osd_job do_image_list $data_path"
    cmds="$cmd1; $cmd2; $cmd3"
    ssh $ssh_option $host $cmds </dev/null
  } &
  done < $osd_host_path
  wait
  echo "$func: finish"
}

function gather_node_infos()
{
  local func="gather_node_infos"
  echo "$func ..."
  >$pg_coll
  >$image_coll_v1
  >$image_coll_v2
  #for host in `cat $osd_host`
  while read line
  do
  {
    host=`echo $line|awk '{print $1}'`
    data_path=`echo $line|awk '{print $2}'`
    echo "$func: $host"
    check_osd_process $host

    #pg epoch
    cmd1="bash $job_path/osd_job cat_pg_epoch $data_path"
    ssh $ssh_option $host $cmd1 >> $pg_coll
    #image v1
    cmd2="bash $job_path/osd_job cat_image_v1 $data_path"
    ssh $ssh_option $host $cmd2 >> $image_coll_v1
    #image v2
    cmd3="bash $job_path/osd_job cat_image_v2 $data_path"
    ssh $ssh_option $host $cmd3 >> $image_coll_v2
  } &
  done < $osd_host_path
  wait
  echo "$func: finish"
}

function scatter_gather()
{
  local func="scatter_gather"
  if [ ! -s $osd_host ];then
    echo "$func: no osd_host input"
    exit
  fi
  if [ ! -s $mon_host ];then
    echo "$func: no mon_host input"
    exit
  fi
  scatter_node_jobs
  gather_node_infos
}


#------------- operations --------------

function database()
{
  scatter_gather
  gen_database
}

function list()
{
  list_images
}

function lookup()
{
  lookup_image $1
}

function recover()
{
  recover_image $1 $2
}

#------------- helper -------------
function usage()
{
  local cmd_name="./admin_job"
  echo "$cmd_name database"
  echo "$cmd_name list"
  echo "$cmd_name lookup <image_name>"
  echo "$cmd_name recover <image_name> [</path/to/store/image>]"
}

function get_path()
{
  local func="get_path"
  if [ "$1"x = ""x ];then
    exit
  fi
  if [[ $1 =~ // ]];then
    exit # "/path//to" is invalid
  fi
  local parent=`dirname $1`
  local name=`basename $1`
  echo -n "$parent/$name"
}

function admin_cmd()
{
  local func="admin_cmd"
  if [ $# -lt 1 ];then
    usage
    exit
  fi
  if [ "$1"x = "-h"x ] || [ "$1"x = "--help"x ];then
    usage
    exit
  fi
  
  if [ "$1"x = "database"x ];then
    if [ $# -gt 1 ];then
      usage
      exit
    fi
    # remove osd_host to refresh osd_host and osd_host_mapping
    rm -f $osd_host
  elif [ "$1"x = "list"x ];then
    if [ $# -gt 1 ];then
      usage
      exit
    fi
  elif [ "$1"x = "lookup"x ];then
    if [ $# -gt 2 ];then
      usage
      exit
    fi
  elif [ "$1"x = "recover"x ];then
    if [ $# -lt 2 ] || [ $# -gt 3 ];then
      usage
      exit
    fi
  elif [ "$1"x = "scp_files"x ];then
    if [ $# -gt 1 ];then
      exit
    fi
    admin_parse_osd
    scp_files
    exit
  elif [ "$1"x = "scp_file"x ];then
    if [ $# -gt 2 ];then
      exit
    fi
    admin_parse_osd
    scp_file $2
    exit
  else
    echo "$func: command $1 not found"
    exit
  fi

  init_env_admin
  local image_path=$3
  if [ "$3"x != ""x ];then
    image_path=`get_path $3`
    if [ "$image_path"x = ""x ];then
      echo "$func: $3 invalid"
      exit
    fi
  fi
  eval "$1 $2 $image_path"
}

admin_cmd $*
