#!/bin/bash
# file: osd_job
# author: min chen(minchen@ubuntukylin.com) 2014

my_dir=$(dirname "$0")

. $my_dir/common_h
. $my_dir/metadata_h
. $my_dir/epoch_h

hostname=`hostname`
hostname="[$hostname]"

function check_ceph_osd()
{
  local func="check_ceph_osd"
  local host=`hostname`
  if [ "`ps aux|grep ceph-osd|grep -v grep`"x != ""x ];then
    echo "$func: [$host] ceph-osd is running..., stop it"
    exit 
  fi
}

function do_omap_list()
{
  local func="do_omap_list"
  #echo -e "$func:\t$hostname start"
  get_omap_list
  #echo -e "$func:\t$hostname finish"
}

# get all pgs epoch 
function do_pg_epoch()
{
  local func="do_pg_epoch"
  #echo -e "$func:\t$hostname start"
  local node=`hostname`
  get_pgid_list
  >$node_pg_epoch
  for pgid in `cat $pgid_list`
  do
  {
    get_pg_epoch $pgid
    #echo -e "$node\t$pgid\t$pg_epoch"
    echo -e "$node $pgid $pg_epoch" >>$node_pg_epoch
  } 
  done
  rm -f $pgid_list
  #echo -e "$func:\t$hostname finish"
}

# get an list of image in this osd node, pg epoch maybe not the latest, the admin node will do distinguish
function do_image_list()
{
  local func="do_image_list"
  #echo -e "$func:\t$hostname start"
  get_image_list   
  local node=`hostname`
  >$image_v1
  >$image_v2
  for line in `cat $image_list_v1`
  do
    #echo "$func: v1  $line"
    pgid=`get_pgid $line`
    get_pg_epoch $pgid
    echo "$node $line $pg_epoch" >> $image_v1
  done
  for line in `cat $image_list_v2`
  do
    #echo "$func: v2  $line"
    pgid=`get_pgid $line`
    get_pg_epoch $pgid
    echo "$node $line $pg_epoch" >> $image_v2
  done
  #echo -e "$func:\t$hostname finish"
}

function do_image_id()
{
  local func="do_image_id"
  get_image_id $1
}

function do_image_metadata_v1()
{
  local func="do_image_metadata_v1"
  local image_header_hobject=$1
  #echo "$func: $1"
  get_image_metadata_v1 $image_header_hobject
}

function do_image_metadata_v2()
{
  local func="do_image_metadata_v2"
  local image_id=$1
  #echo "$func: image_id = $imag_id"
  local image_header_hobject=$2
  get_map_header $image_id 
  #echo "$func: map_headaer_prefix = $map_header_prefix"
  #echo "$func: map_headaer_key = $map_header_key"
  get_meta_header_seq $map_header_prefix $map_header_key
  #echo "$func: meta_headaer_seq = $meta_header_seq"
  get_image_metadata_v2 $meta_header_seq
}

check_ceph_osd
init_env_osd
$*
