#!/bin/bash
# file: osd_job
# author: min chen(minchen@ubuntukylin.com) 2014 2015

my_dir=$(dirname "$0")

. $my_dir/common_h
. $my_dir/metadata_h
. $my_dir/epoch_h

hostname=`hostname`
hostname="[$hostname]"

function check_ceph_osd()
{
  local func="check_ceph_osd"
  local host=`hostname`
  if [ "`ps aux|grep ceph-osd|grep -v grep`"x != ""x ];then
    echo "$func: [$host] ceph-osd is running..., stop it"
    exit 
  fi
}

function cat_pg_epoch()
{
  local func="cat_pg_epoch" 
  init_env_osd $1
  if [ -e $node_pg_epoch ];then
    cat $node_pg_epoch
  fi
} 

function cat_image_v1()
{
  local func="cat_image_v1" 
  init_env_osd $1
  if [ -e $image_v1 ];then
    cat $image_v1
  fi
} 

function cat_image_v2()
{
  local func="cat_image_v2" 
  init_env_osd $1
  if [ -e $image_v2 ];then
    cat $image_v2
  fi
} 

function do_omap_list()
{
  local func="do_omap_list"
  init_env_osd $1
  get_omap_list
}

# get all pgs epoch 
function do_pg_epoch()
{
  local func="do_pg_epoch"
  init_env_osd $1
  local node=`hostname`
  get_pgid_list
  >$node_pg_epoch
  local pgid=
  local data_path=
  while read line
  do
  {
    pgid=`echo $line|awk '{print $1}'`
    data_path=`echo $line|awk '{print $2}'`
    get_pg_epoch $pgid
    echo -e "$node $pgid $pg_epoch $data_path" >>$node_pg_epoch
  } 
  done < $pgid_list
}

# get an list of image in this osd node, pg epoch maybe not the latest, the admin node will do distinguish
function do_image_list()
{
  local func="do_image_list"
  init_env_osd $1
  get_image_list   
  local node=`hostname`
  >$image_v1
  >$image_v2
  for line in `cat $image_list_v1`
  do
    pgid=`get_pgid $line`
    get_pg_epoch $pgid
    echo "$node $line $pg_epoch" >> $image_v1
  done
  for line in `cat $image_list_v2`
  do
    pgid=`get_pgid $line`
    get_pg_epoch $pgid
    echo "$node $line $pg_epoch" >> $image_v2
  done
}

function do_image_id()
{
  local func="do_image_id"
  init_env_osd $1
  get_image_id $2
}

function do_image_metadata_v1()
{
  local func="do_image_metadata_v1"
  init_env_osd $1
  local image_header_hobject=$2
  local snap_name=$3
  get_image_metadata_v1 $image_header_hobject $snap_name
}

function do_image_metadata_v2()
{
  local func="do_image_metadata_v2"
  init_env_osd $1
  local image_id=$2
  local image_header_hobject=$3
  local snap_name=$4
  get_map_header $image_id 
  get_meta_header_seq $map_header_prefix $map_header_key
  get_image_metadata_v2 $meta_header_seq $snap_name
}

check_ceph_osd
$*
